apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ph01xie44-go-gitops
  description: This is GitOps manifest for ph01xie44-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ph01xie44-go
    backstage.io/kubernetes-id: ph01xie44-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ph01xie44-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ph01xie44-go
